### ISSUE TITLE
panel for tracy, not for nette

### ISSUE THREAD

**Issue by miloslavkostir** [repli2dev/tracy-gitversion-panel#1]
This addon is for Tracy, but usage in readme.md is written for Nette\Configurator  
This is registration for nette configuration file:

```
nette:
    debugger:
        bar: [JanDrabek\Tracy\GitVersionPanel]
```

and registration for Tracy\Bar should be something like this:

``` php
Tracy\Debugger::getBar()->addPanel(new JanDrabek\Tracy\GitVersionPanel());
```

It's just detail, but could be unintelligible for someone.

**Comment by repli2dev** [comment]
Well this addon is quite polymorphic (is for tracy as well as Nette). I reflected that in new version README.

**Comment by miloslavkostir** [comment]
Great solution
